### ISSUE TITLE
Binance/Bitrex sync broken?

### ISSUE THREAD

**Issue by t0cc** [jkcdarunday/minotaur-plasmoid#1]
Hi, it looks like syncing with exchanges doesn't work anymore.

**Comment by jkcdarunday** [comment]
Hi, mine is still syncing. Though the price did freeze a few months ago when crypto prices skyrocketed but that was due to most exchanges (including Binance and Bittrex) having network performance issues.

Does this issue still occur as of today?

**Comment by jkcdarunday** [comment]
Closing this issue as I cannot replicate it. Please file a new one in case it occurs again. Thanks!
